---
title: Are paying customers happy customers?
author: Oz Guner
date: '2023-06-19'
slug: are-paying-customers-happy-customers
categories:
  - class notes
tags:
  - marketing
  - revenue
subtitle: 'Acquiring new business is fantastic, but creating an environment for retaining existing customers is where the real value lies.'
excerpt: 'Acquiring new business is fantastic, but creating an environment for retaining existing customers is where the real value lies.'
summary: 'Acquiring new business is fantastic, but creating an environment for retaining existing customers is where the real value lies.'
keywords: ['paying customers', 'happy customers', 'SaaS businesses', 'recurring basis', 'NPS surveys', 'user onboarding', 'Slack', 'customer retention', 'existing customers', 'user realizing value']
draft: no
series: ~
layout: single-sidebar
---
Are you wondering if paying customers are truly happy customers? This is a question that has been on my mind lately, especially considering the large number of users in SaaS businesses who pay for their subscriptions on a recurring basis, often upfront. In my recent conversation with Aseem Chandra, I mentioned that some of our paying customers had been facing certain issues for years, yet they continue to remain loyal and pay for our services. We have taken action by allocating resources to address these issues, but this left me with a question: Are paying users necessarily happy?

Ramli John's Product-Led Onboarding is a good entry-level source albeit feels repeated at times. Ramli talks about how Slack solved this problem. Slack doesn't assume that a client is somehow instantly happy because they started paying and using the product. They analyzed the data and decided that you'd need to send 2,000 messages to realize the value and be happy with the product. Any issues you have with the product would surface until you hit that number. CEO and co-founder of Slack, noted that 93% of teams that surpassed that number are still using Slack today. This is a powerful retention story.

Acquiring new business is fantastic, but creating an environment for retaining existing customers is where the real value lies. In established SaaS businesses, the existing customer base typically accounts for over 50% of total revenue. Consequently, the user onboarding process plays a pivotal role in helping users realize the value of the product and in ensuring customer retention.
